apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedmabdi/EKS.git
    targetRevision: HEAD
    path: apps       
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true