apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedmabdi/EKS.git
    targetRevision: HEAD
    path: apps/umami
  destination:
    server: https://kubernetes.default.svc
    namespace: umami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true