apiVersion: v1
kind: Namespace
metadata:
  name: umami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  namespace: umami
  labels:
    app: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
      - name: umami
        image: 471112781681.dkr.ecr.eu-west-2.amazonaws.com/umami:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: umami-db-secret
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: umami-service
  namespace: umami
spec:
  selector:
    app: umami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami-ingress
  namespace: umami
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - umami.ahmedumami.click
    secretName: umami-tls
  rules:
  - host: umami.ahmedumami.click
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: umami-service
            port:
             number: 80
  tls:
  - hosts:
    - umami.ahmedumami.click
    secretName: umami-tls 